### PR TITLE
[CMS-718] Update dependencies

### PR DESCRIPTION
**Pull request by jspellman814**

### CODE REVIEW

**Review by jazzsequence — APPROVED** [review]
👍  lgtm :shipit:

**Comment by jazzsequence** [comment]
I noticed that `pantheon-systems/pantheon-wp-main` doesn't exist yet. What's going in there?

**Comment by jspellman814** [comment]
https://packagist.org/packages/pantheon-systems/pantheon-wp-main maps to https://github.com/pantheon-systems/wp-main. Not sure why the names differ though - @rwagner00 any insight on that? Any issue with renaming the packagist package to `wp-main` so the names match? Don't believe I have the permissions to do that.

**Comment by jazzsequence** [comment]
Got it! No worries then! I'm not unfamiliar with Packagist packages having a different name than their GH repositories. 👍

**Comment by jspellman814** [comment]
Cool I'll merge this as is, and we can adjust the Packagist name at a later time if we decide to do so.

**Pull request merged**
